import Link from 'next/link';

import { getAdminOrders } from '@/server/admin/orders';

export default async function AdminOrdersPage() {
  const orders = await getAdminOrders();

  return (
    <main style={{ display: 'grid', gap: 24 }}>
      <div>
        <h1 style={{ margin: 0 }}>Orders</h1>
        <p style={{ margin: '8px 0 0', color: '#677489' }}>Real order records generated by checkout now appear here for operations review.</p>
      </div>
      {!orders.length ? (
        <article className="info-card">
          <h2>No orders yet</h2>
          <p className="section-description">Once a member completes checkout, the order list and detail pages will populate automatically.</p>
        </article>
      ) : (
        <div className="info-grid">
          {orders.map((order) => (
            <article key={order.id} className="info-card" style={{ display: 'grid', gap: 10 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}>
                <h2 style={{ margin: 0 }}>{order.orderNumber}</h2>
                <span className="product-badge">{order.status}</span>
              </div>
              <p style={{ margin: 0, color: '#677489' }}>{order.customerName} {order.customerLastName} · {order.customerEmail}</p>
              <p style={{ margin: 0, color: '#677489' }}>Payment: {order.paymentMethod ?? 'Not set'} · Shipping: {order.shippingMethod ?? 'Not set'}</p>
              <p style={{ margin: 0 }}><strong>${Number(order.totalAmount).toFixed(2)}</strong></p>
              <Link href={`/admin/orders/${order.orderNumber}`}>Open order detail</Link>
            </article>
          ))}
        </div>
      )}
    </main>
  );
}
